// code below generated by template: https://github.wdf.sap.corp/I532140/andrewy-sap
public enum SFNavigationID:String {

    // empty id for debugging
    case placeHolder = ""
    
    {% for navi in ids %}
    // module: {{navi.module}}
    // naviId: {{navi.navigationId}}
    // use case: {{navi.useCase}}
    // user story: {{navi.userStory}}
    case {{(navi.action.lower()+navi.entity).replace(".", "_")}} = "{{navi.navigationId}}"
    {% endfor %}
}